# thameswater is written in Python...
language: python

# and we're only going to validate against Python 3.6
python:
  - "3.6"

#variables:
#  PACKAGE_NAME: thameswater
  

# Make sure that we install pylint and flake8
#install: 
#  - pip install -r requirements.txt

script:
  # - pip install flake8 pylint
  - flake8 thameswater
  - pylint thameswater/thameswater.py
#  - deploy

deploy:
  on:
    branch: 0.2
    python: '3.6'
  provider: pypi
  # Work around current PyPi/Travis issues.
  edge:
    branch: v1.8.45
  user: "papadeltasierra"
  password:
    secure: "e7AjBloTdeJyLsxMIvElCuzX+goD7TBDNwezodNRWmtYvIuEbD4tXJ2sfN6jfwya9Dv82Oskyno2ctmiqRNOWr8/7P7u9/499xrZCAtJbXIwNkMXSK4EfWjmuEvlWXBQgAQsWf1wKwdY3SMsd1R0s4Ysj7go9LTUjvVyrkWW/b2bCVdlZj5/zVdixE+YvfWcmRfUkI36HyrF8Uuwbp70upQF8QwncJU4NWak8KcanodCm9Mu9TOLbtpdk68STE0YGB4OwdzZT65D5xLeEroZXdNfuWrKEuvL8FuOAflxQoXfMBd4kNHUyxi38VHZvq/FK/DBE17MgZm7giYbrOrddc0BgyAaBEwuI4jjuPkUUvFMrOuaYb/pOvnUE2jPh2YtoK6JrzXhzTZv+Pzwo8/Bxy//VvkdVt0JzT5+/werdJhDQOSRZOHL6jtS5Wmq87z0joxX0H2AItumNo9N+YeBOQMSwLuO/ZiQyykL5eFv+kz6PkqEos1cffdI5huWmRlaNMxKgJi/zZ2a3YZ/rNKUK/GZSZbCVKhlIW4i7H86DD1kfCbzQab4jZdpZjPqObGSx+qQK/BHyznaU5EOx3cbdOaXu4bA7snEdUMprHSeogjkrC4n2y6nWB3NtwHPEol5HTFr0AVG+wXcO/oJCZwAw7Cbesx3ZaKejs1Tkj1IFas="
#security_lint:
#  <<: *setup_lint
#  stage: lint
#  script:
#    - pip install bandit
#    - mkdir -p output/bandit_logs
#    - bandit -a file -r . -f html -ll -o output/bandit_logs/report_medium_high.html
#  artifacts:
#    when: on_failure
#    paths:
#      - output/bandit_logs
#    expire_in: 1 day

#deploy:
#  image: python:3.6
#  stage: deploy
#  environment:
#    name: production
#  script:
#    - pip install --upgrade pip --quiet
#    - pip install setuptools wheel --quiet
#    - python setup.py sdist bdist_wheel upload
#  when: manual
#  only:
#    - /^v?\d+\.\d+\.\d+([abc]\d*)?$/
#  except:
#    - branches
