language: python
python:
<<<<<<< HEAD
  - "3.6"

#variables:
#  PACKAGE_NAME: thameswater


# Make sure that we install pylint and flake8
#install:
#  - pip install -r requirements.txt

=======
- '3.6'
>>>>>>> master
script:
- flake8 thameswater
- pylint thameswater/thameswater.py
deploy:
  on:
<<<<<<< HEAD
    branch: '0.3'
=======
    branch: 0.0.2
>>>>>>> master
    python: '3.6'
  provider: pypi
  user: papadeltasierra
  password:
    secure: J0eju2Vy/NCC75cjGtGpaG4jtahl3n6ZbrylyC5ZJt+SfWcQZGzNjlT+VVXya4Z+hsoPpy8PpPJzmSAE2DdXTYjcBmvWTwwpzzbGaCyhE6+LwP91WP6EHV5VAN0EbyQHByu15tok/ytGASkBdrX3t4sh55z5TUf0gfbramTDTBxQ6gea3JuvoiWMUV2tMVRzUY4X3leaQljZDmAE0h9V6RxTsp0xZaU7jg8KJ6Oa0CBS5n+UTU/L5u0KEXFKHQQIAwl/d2UcGbUXCAsqe0Ls5lUMSVd5S9uVFRT6PND7nDOuVxZ8RHEI3kPaayOgQfPJyDYg+4q/r1luWlPlW5BYAYUWc70SMW5AbXxw4uwF7fmxm1Wi3PoRF13Wk8tR87ZvgRmLd/0OVdldrO70YUxlNpOwcfexUp6nHY81uBmE2w69p2E9ALH05Gwk8TlqZsbdA5KYyDSYez5aZ6IanNCinlVyeKbKxUowsdQHrl3jGxv6knpz6aGkLfm6mqB7vLNbxc9a42iPNJPBFBeaWwQbCMbM8r+drrYxxq04IxnjJ9Yi9aCa9BJ0Hl7MF8fep/AFhClx2mVy5BpJ7nKNOMWM2ggmlDQtAuMfkYdIxo4r+TkvUtM12ex2StUV+K6BMXG2vgkApAyaGsG+eMmH8DKzhPc6nruPjS4KmojoWAwqUMI=
