# thameswater is written in Python...
language: python

# and we're only going to validate against Python 3.6
python:
  - "3.6"

#variables:
#  PACKAGE_NAME: thameswater
  

# Make sure that we install pylint and flake8
#install: 
#  - pip install -r requirements.txt

script:
  # - pip install flake8 pylint
  - flake8 thameswater
  - pylint thameswater/thameswater.py
#  - deploy

deploy:
  on:
    branch: 0.2
    python: '3.6'
  provider: pypi
  # Work around current PyPi/Travis issues.
  edge:
    branch: v1.8.45
  user: "papadeltasierra"
  password:
    secure: "NSgZjXf8JN/3Cgfax4ilY/awgcCjDSaxL2dDF/sNKr8qz2t5dXzii0eY7KKlMIJ30uhQsdY/PrfLhENZy9sNHG86FN1PMdCFGLL/TS3iXg2/C8wcuNO1VHRFM861uwTe+69CbhLJAUwKOY0XyXI/X2azFSDb5uerN0L2iLFa9+VCROavju1ntBtNBDHjtVElL/LkG8TfUjR5uClQTiT70xfpnJe49pF0Zgnork76/EzbifQFhvgg+ToMCIxHlWlsp5qwnRhOpr/3BQFL2ELA5zqL/eRFEhhlcOXty/crGhGc+ZP87Lpyg69GsVczakU0kyeOrHAQhxj/Jdag+/yCSJEOjr6GuHQ/t+fJH134P2oK+o+wIrBHyH9K4duRINFwCifP/4kDhCU10DEqCg0PjioyQUR41HBIFaaomRKA9WkKdbdCQLBFN5eZ6mFf2uBKRPDF3mHGLX/qjvXTH9euOGBDZGFUlrcYuMVKLoPWS8aV1fzuwg0jKfp2UqWYOdXipBGaqMnO3Ik0K5IruL1lrQV/7HPOp0ENmJyRhLPqgeOs4hbnEIfukvBxSQsmEg+uCPLw+Dmr9KzPg90NriOFuDw7fcgTrQo/Lh5jKsaUcxO0I0KZZB9ljzXCPds3QfGSsPNQoy5ZlURiW+lr0IYN2HFjrjQEBJk7OuTNcQSctIY="
#security_lint:
#  <<: *setup_lint
#  stage: lint
#  script:
#    - pip install bandit
#    - mkdir -p output/bandit_logs
#    - bandit -a file -r . -f html -ll -o output/bandit_logs/report_medium_high.html
#  artifacts:
#    when: on_failure
#    paths:
#      - output/bandit_logs
#    expire_in: 1 day

#deploy:
#  image: python:3.6
#  stage: deploy
#  environment:
#    name: production
#  script:
#    - pip install --upgrade pip --quiet
#    - pip install setuptools wheel --quiet
#    - python setup.py sdist bdist_wheel upload
#  when: manual
#  only:
#    - /^v?\d+\.\d+\.\d+([abc]\d*)?$/
#  except:
#    - branches
